version: '3'

networks:
  168H:
    driver: bridge
    ipam:
          config:
            - subnet: 192.168.0.0/24
services:

  back:
    build: ./back
    ports:
      - "5001:5001"
    volumes:
      - ./back/generated:/var/reports
    networks:
          - 168H
  front:
    build: ./front
    ports:
      - "3000:3000"
    # volumes:
    #   - ./front/scanreport/node_modules:/app/node_modules
    networks:
          - 168H

  vulnerable_container:
    image: webgoat/webgoat
    ports:
      - "8080:8080"
    networks:
      168H:
        ipv4_address: 192.168.0.100